<a href="https://colab.research.google.com/github/Kelvin1006/data_science_tutorial/blob/main/Tutorial03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
#1.Create a numpy array of size 2 x 2
array2x2=np.array([[1,0],[0,6]])
print(array2x2)

[[1 0]
 [0 6]]


In [12]:
#2.Create a random numpy array of size 3 x 4
randomarray3x4 = np.random.rand(3, 4)
print(randomarray3x4)

[[0.70202122 0.26667987 0.17446025 0.2451851 ]
 [0.67247755 0.55276846 0.73393864 0.60779955]
 [0.51280969 0.81255871 0.72233347 0.77224253]]


In [17]:
#3. Create a numpy array of ones and a numpy array of zeroes
arrayofones = np.ones((10, 6))
print("Numpy array of ones:")
print(arrayofones)

arrayofzeroes = np.zeros((6, 7))
print("Numpy array of zeroes:")
print(arrayofzeroes)

Numpy array of ones:
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
Numpy array of zeroes:
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [20]:
#4. Create a random numpy array of size 6x3 and transpose it
randomarray6x3 = np.random.randint(0,10,size=(6, 3))
print(randomarray6x3)
transposedarray = randomarray6x3.T
print("Transposed array:")
print(transposedarray)

[[6 5 2]
 [8 1 3]
 [8 6 0]
 [9 9 2]
 [7 7 7]
 [1 5 9]]
Transposed array:
[[6 8 8 9 7 1]
 [5 1 6 9 7 5]
 [2 3 0 2 7 9]]


In [23]:
#5. Create two random numpy array of size n x p and p x m and then compute the dot product
n,p,m=3,4,3
randomarray1 = np.random.rand(n, p)
randomarray2 = np.random.rand(p, m)
print("Random array 1:")
print(randomarray1)
print("Random array 2:")
print(randomarray2)

dotproduct = np.dot(randomarray1, randomarray2)
print("Dot Product:")
print(dotproduct)

Random array 1:
[[0.52428436 0.73363051 0.84386585 0.01214236]
 [0.11081806 0.33347945 0.18931235 0.2631409 ]
 [0.71910423 0.19413997 0.59715197 0.46944407]]
Random array 2:
[[0.28447407 0.37128387 0.94497672]
 [0.88699963 0.74718385 0.35864545]
 [0.46876946 0.72388259 0.39772735]
 [0.05816691 0.40383563 0.2704194 ]]
Dot Product:
[[1.19616012 1.35857851 1.09746182]
 [0.43137095 0.533621   0.37077448]
 [0.6840013  1.0338962  1.11361463]]
